### ISSUE TITLE
bootstrap.enrichment.test returns error about cantrecognize gene

### ISSUE THREAD

**Issue by WeiCSong** [NathanSkene/EWCE#1]
HI EWCE developer,i used EWCE to analyse my data:
    `full_results = bootstrap.enrichment.test(sct_data=merged_KI,hits=list,bg=bg,sctSpecies = "human", 
 genelistSpecies = "human",reps=10000,annotLevel=1)`
and i got error:

> ERROR: At least four genes which are present in the single cell dataset & background gene set are required to test for enrichment
But i dont think this is true for me:
`length(intersect(rownames(merged_KI$exp),bg))`

> 10622
So I cant understand what this error actually means.Wish to get help from you.Thanks!

**Comment by NathanSkene** [comment]
Hi,

This is a very late response, but the input to bootstrap.enrichment.test should have the same format as the ctd used in the tutorial.
