### ISSUE TITLE
Calculating cell type specificity scores

### ISSUE THREAD

**Issue by tkamath1** [NathanSkene/EWCE#10]
Hi! Thanks for the great package.

I'm interested in running the cell type specificity score calculation for some 10x snRNA-seq datasets. Is there a clear reason to use either mean or median for zero-inflated datasets?

Also, curious for the rationale of dividing the median scores by colSums of the mean per cell type/subtype as opposed to the colSums of the median ("generate.celltype.data.R", lines 89/91)?

**Comment by NathanSkene** [comment]
Hi Tushar,

I recommend mean over median. Median tends to be uninformative as most genes have a median of zero. 10x data is not actually zero inflated, it is just negative binomial distributed (unlike Smart-Seq data does appear to be zero inflated). The mean of a sample from a negative binomial distribution is an estimate if the real population mean (unlike the median).

Hope that helps


On 24/10/2019 15:15, Tushar Kamath wrote:

Hi! Thanks for the great package.

I'm interested in running the cell type specificity score calculation for some 10x snRNA-seq datasets. Is there a clear reason to use either mean or median for zero-inflated datasets?

Also, curious for the rationale of dividing the median scores by colSums of the mean per cell type/subtype as opposed to the colSums of the median ("generate.celltype.data.R", lines 89/91)?

**Comment by tkamath1** [comment]
Thanks!
