### ISSUE TITLE
Setup unittesting with testthat

### ISSUE THREAD

**Issue by NathanSkene** [NathanSkene/EWCE#26]

**Comment by Al-Murphy** [comment]
Just assuming this is the initial set up to enable unit testing and not the addition of further tests? If so this was completed with the mean CTD test

**Comment by NathanSkene** [comment]
I was thinking addition of extra tests, idea is that codecov should report at least 80% covered by tests

Additional tests could be:

- Running `cortex_mrna$exp = fix.bad.mgi.symbols(cortex_mrna$exp,mrk_file_path="MRK_List2.rpt")` (from the vignette) removes/fixes an expected set of genes

- Running `full_results = bootstrap.enrichment.test(sct_data=ctd,hits=mouse.hits,bg=mouse.bg,reps=reps,annotLevel=level)` gives microglia as the only significant enrichment

- Running `tt_results = ewce_expression_data(sct_data=ctd,tt=tt_alzh,annotLevel=1,ttSpecies="human",sctSpecies="mouse")` gives the results shown in the vignette

- Also include a test for `controlled_geneset_enrichment`

Because EWCE uses random permutations, the 'same result' should not depend on exact pvalues.

**Comment by NathanSkene** [comment]
Another test:
- Iba1 is most specific to microglia (based on sorting of specificity matrix)
- Pvalb is most specific to interneurons (based on sorting of specificity matrix)
