### ISSUE TITLE
Setup one initial unit test with testthat and understand how it works with travis

### ISSUE THREAD

**Issue by NathanSkene** [NathanSkene/EWCE#29]
A good initial test would be to confirm that when a simple CTD is created, the mean is calculated correctly (I did actually have an edit a while back, that was intended to speed up generation of the CTD, which meant it stopped calculating the mean properly)

**Comment by NathanSkene** [comment]
Can't see where the actual test is in this commit: https://github.com/NathanSkene/EWCE/commit/b8904802bdec92c97501786636f1f9aef65100aa

Can only see where testthat was added to travis.yml and description?

**Comment by Al-Murphy** [comment]
Sorry, my fault, I didn't commit the test folder in the dev-Initaltestthat commit. However, if you look in the dev branch in EWCE/test/ you will find it there. Once I have an issue sorted I'll commit it to dev.
