### ISSUE TITLE
Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead

### ISSUE THREAD

**Issue by liuhankui** [NathanSkene/EWCE#34]
This last version seems to use ExperimentHub for doing something when I perform bootstrap_enrichment_test.
However, in some cases, we do not connect to the internet or cannot access the web service of bioconductor.org.
Even I set ExperimentHub(localHub=T), I still not have a local cache.
So, I can not use this package anymore.

**Comment by liuhankui** [comment]
I guess the issue comes from check_ewce_genelist_inputs

**Comment by NathanSkene** [comment]
Hey Alan, any thoughts on this one?

**Comment by Al-Murphy** [comment]
Hi @liuhankui,

A requirement of Bioconductor is that no large (>5kb) data files can be included in the package submission. The workaround is to submit reference datasets to ExperimentHub. `bootstrap_enrichment_test` uses reference datasets to run, for example, to check if the inputted human gene lists have mouse homologs by calling `check_ewce_genelist_inputs` (as you pointed out). The relevant dataset is: 

```
eh <- ExperimentHub::ExperimentHub()
eh[["EH5367"]])
```

Can I ask why you need to run EWCE offline? The reference datasets were not set up to allow local calls to ExperimentHub, see [neurogenomics/ewceData/utils.R](https://github.com/neurogenomics/ewceData/blob/main/R/utils.R) and the `get_ExperimentHub` function. To rewrite EWCE and ewceData to allow localHub runs would take a significant amount of work given the necessary propagation of a parameter through all instigated EWCE functions so I would like to understand the need.

Thanks,
Alan.

**Comment by liuhankui** [comment]
> Hi @liuhankui,
> 
> A requirement of Bioconductor is that no large (>5kb) data files can be included in the package submission. The workaround is to submit reference datasets to ExperimentHub. `bootstrap_enrichment_test` uses reference datasets to run, for example, to check if the inputted human gene lists have mouse homologs by calling `check_ewce_genelist_inputs` (as you pointed out). The relevant dataset is:
> 
> ```
> eh <- ExperimentHub::ExperimentHub()
> eh[["EH5367"]])
> ```
> 
> Can I ask why you need to run EWCE offline? The reference datasets were not set up to allow local calls to ExperimentHub, see [neurogenomics/ewceData/utils.R](https://github.com/neurogenomics/ewceData/blob/main/R/utils.R) and the `get_ExperimentHub` function. To rewrite EWCE and ewceData to allow localHub runs would take a significant amount of work given the necessary propagation of a parameter through all instigated EWCE functions so I would like to understand the need.
> 
> Thanks,
> Alan.

Hi, Alan,
Thank you for explaining why the issue coming out.  

The reason I run EWCE offline is that I am calculating the specificity of a large-scale sc-RNA data in local high-performance computing cluster, where has no connection of the Internet. Most of the time, I performed this kind of study on personal computer. But, as we knew, in the future there will be more and more sc-RNA data, which may require a special computing environment. Please take your time to consider the necessity of rewriting EWCE. There are several ways to figure out this issue. I have calculated the specificity matrix and transferred the matrix to personal computer and run bootstrap_enrichment_test on PC. I can also edit the check_ewce_genelist_inputs function and recompile the package and check the gene list myself. But this way may be challenging for someone who is not good at R program.

Best,
Hankui.

**Comment by Al-Murphy** [comment]
I've created this as issue to go in our dev backlog. Thank you Hankui for pointing this out and note, we will make the change for a future release of EWCE. I'll close this issue for now but do get in touch if something else comes up.

Thanks,
Alan.
