### ISSUE TITLE
Enable offline runs of EWCE with ExperimentHub

### ISSUE THREAD

**Issue by Al-Murphy** [NathanSkene/EWCE#35]
Enable EWCE to run offline by using local cache of ExperiementHub. Issue was highlighted [here](https://github.com/NathanSkene/EWCE/issues/34) by a user.

This will require:

* Updating ewceData so that the neurogenomics/ewceData/R/utils.R and the get_ExperimentHub function along with all dataset functions handle a localHub=T parameter
* Update all EWCE functions that call and load datasets from ewceData with the parmeter. The parameter will need to propagate up through the functions.
* Add a test case
* Push to Bioconductor

**Comment by chrisclarkson** [comment]
Hi Thank you for making this resource available!
I too work on a cluster that is closed off from the internet (which is obviously beyond your control)... which is making it difficult to use your package:
![image](https://user-images.githubusercontent.com/26774207/213439843-17f27a8e-4e0e-441f-b983-4bbef8d6b2e0.png)
I tried testing the ExperimentHub problem directly (with localHub=T):
![image](https://user-images.githubusercontent.com/26774207/213440606-a2318a5a-2404-4f13-8661-c2bf27e5fdb7.png)

and localHub=F:
![image](https://user-images.githubusercontent.com/26774207/213440235-2d661831-a180-499c-9438-6a83acc40b7c.png)

and so I tried downloading the sqlite database directly:

![image](https://user-images.githubusercontent.com/26774207/213440537-367dd0d4-80e4-4423-9f98-d99873bc6599.png)

And it seems to have worked...

Looking inside the ~/.cache/R/ExperimentHub/ databases:
![image](https://user-images.githubusercontent.com/26774207/213441336-5040c04c-d3b1-4b91-a93d-b7d3b41262e9.png)
It seems that certain data might be missing from the `resource` table.
But the downloaded `experimenthub.sqlite` data seem to be intact(?):
![image](https://user-images.githubusercontent.com/26774207/213441853-1022aeb0-8455-46fb-a1a9-63872b8024f7.png)

Hence I am wondering if there is some way that I can just add the `experimenthub` data manually to your `BiocFilecache` database to get the package working for me....?

A lofty ask- I know- but appreciate any advice you can give.
Kind Regards

**Comment by Al-Murphy** [comment]
Hey,

Thanks for your message. I have been meaning to make the change so you can run EWCE offline with the localHub approach for some time now so this has convinced me to do it. I will update this issue once it's done.

In terms of your ask though, I don't think we could/should add this data to the BiocFileCache given that adding these to the experimenthub database is the best practice and gives use a single location for version control, access etc. When I do make the change to enable localHub offline runs I think your best option is to get on to the bioconductor maintainer of experimenthub to find out how best to cache a local version of the files you need and copy them to a location in your closed cluster where they can be accessed when you run your analysis. Otherwise, it might be worth running this step locally, often EWCE runs don't use a lot of RAM although this does vary vastly on the dataset.

Hope this helps!
Alan.

**Comment by chrisclarkson** [comment]
Thanks for the quick reply- so ultimately I should be able to copy some data onto my local cluster and use one of your inhouse EWCE commands to add these data in a way that I can then analyse them with `EWCE::plot_mean` etc.

**Comment by Al-Murphy** [comment]
The necessary changes have now been made to run EWCE offline - the instigated functions have been documented, I've also updated the vignettes so check these for more info.

On you issue, I'm not sure this will work as I haven't done it before (why I think you should get in touch with the maintainers of Experimenthub) but it makes sense to me since the caching stores a version of the experimenthub database that you could just copy this from your local machine to your HPC. You would need to be sure your HPC experimenthub call is pointing to the correct location.

I'm going to close this issue since this is all we can do from our end with EWCE but do feel free to reopen if you have any issues running EWCE with localhub = TRUE
