### ISSUE TITLE
Imputed data for EWCE object

### ISSUE THREAD

**Issue by kvshams** [NathanSkene/EWCE#36]
Is it possible to use an imputed matrix (eg: MAGIC) to construct the EWCE object?

**Comment by Al-Murphy** [comment]
Hi @kvshams,

Magic is not dissimilar to scTransform, which EWCE already makes use of in the [vignette](https://nathanskene.github.io/EWCE/articles/EWCE.html). So there is no reason it cannot be used. Note however, whether the data was passed through scTransform or not, did not seem to make a big difference to EWCE's results in our testing.

Thanks,
Alan.
