### ISSUE TITLE
Docker issues

### ISSUE THREAD

**Issue by bschilder** [NathanSkene/EWCE#54]
Docker container of EWCE works fine until you try to print some plots. 

Just noticed this warning message:
```
R graphics engine version 15 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed. 
```

Apparently this happens when the version of R is too far ahead of the version of Rstudio. For some reason there is no back compatibility? 
https://community.rstudio.com/t/warning-message-r-graphics-engine-version-14-is-not-supported-by-this-version-of-rstudio-the-plots-tab-will-be-disabled-until-a-newer-version-of-rstudio-is-installed/110386

## Source

Our Dockerfile currently uses `bioconductor/bioconductor_docker:devel` as the base. Which means that this is an issue with how Bioconductor is setting up their docker container, not ours.

## Potential solutions

We could try changing our Dockerfile to one of the following:
- `bioconductor/bioconductor_docker:latest`: May not always be accurate. Maintainer [doesn't seem keen on keep this up to date](https://github.com/Bioconductor/bioconductor_docker/issues/29), though a verdict on this was never communicated.
- `bioconductor/bioconductor_docker:RELEASE_3_14`: Should work, but means we will have to remember to manually update the Dockerfile anytime there is a new release. My intent with using the`latest` tag was to avoid this and make the file usable in the long-term as is.

Or we could simply wait until the bioconductor_docker maintainer fixes the issue, and then rebuild any containers that used that version. I've posted the Issue here:
https://github.com/Bioconductor/bioconductor_docker/issues/39

**Comment by Al-Murphy** [comment]
Based on what you have here, makes most sense to me to wait to see if a fix is put in by the bioconductor_docker maintainer. The way you currently have the automated docker builds set up is the most logical.

**Comment by bschilder** [comment]
This has since been resolved after the bioconductor_docker update.
