### ISSUE TITLE
EWCE:::is_celltypedataset. Does not state why the cell type data is not valid. 

### ISSUE THREAD

**Issue by roxyisat-rex** [NathanSkene/EWCE#55]
When ctd is missing cell level data which is "annot"  (i.e. the assigned cluster of each cell). EWCE will not run. However, it will not explicitly tell you that it is missing this particular feature. 

```
EWCE:::is_celltypedataset(MAGMA.Celltyping::ctd_Zeisel2018)
```
```
[1] FALSE
```

**Comment by bschilder** [comment]
This was due to the `standardise_ctd` function not generating the annot sublist in the correct part of the CTD. I've since fixed this and have regenerate and reuploaded  all the CTDs distributed via `MAGMA.Celltyping`.
