### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by alexandruioanvoda** [NathanSkene/EWCE#6]
Hi, can `generate.celltype.data()` get a progress bar? There are some huge expression matrices that we're working with and it'd be really useful.

**Comment by NathanSkene** [comment]
I’d be happy to pull in the code for it if you are up for modifying the function! I’m not sure it would work properly though given that the function uses mclapply.

I wrote a version of the function recently which takes a loom file as input. Might work faster if your expression matrix is huge. I’ve attached it to this email… it was written specifically for a dataset I was working on so can’t guarantee it’s “package ready”.
