### ISSUE TITLE
Run Cell-type Enrichment Tests on Two Annotation Levels

### ISSUE THREAD

**Issue by h1hui** [NathanSkene/EWCE#65]
Hello,

I know I can input many annotation levels with the ctd, but can you run bootstrap_enrichment_test on two annotation levels at the same time? Because we have three patient types, and different cell types, we want to be able to compare all of them together. Is there any way that you can do that?

Thanks,
Ashley

**Comment by bschilder** [comment]
If you want to test both cell-type levels, just run `bootstrap_enrichment_test` twice (once per level).
You can always `rbind` the results table later. 

Please do make use of the templates when you open a new issue this will help us to help you faster. Thanks!

**Comment by h1hui** [comment]
But I would like to be able to compare both levels at the same time. Does using rbind make the results comparable afterwards (like p values, fold_change, and sd_from_mean)?

**Comment by bschilder** [comment]
`rbind`is just a base function in R that stacks two data.frames on top of each other.

Yes, I believe that should be comparable across runs. Only other thing i'd recommend is recomputing your FDR column (False Discovery Rate) to account for the two round of testing you did. [`p.adjust`](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/p.adjust) makes this easy.
