### ISSUE TITLE
Proportional expression of individual hit genes

### ISSUE THREAD

**Issue by h1hui** [NathanSkene/EWCE#67]
**Is your feature request related to a problem? Please describe.**
Is there any way to extract this proportional expression gene matrix, and plot?

**Describe the solution you'd like**
I want a function that can calculate the proportional expression across an annotation level, for each of the genes in the hits.

**Describe alternatives you've considered**

**Additional context**
I was reading this paper https://www.nature.com/articles/s41586-021-04369-3, and in Figure 6A, they were able to plot this as a heatmap, as shown.
![Screen Shot 2022-05-17 at 2 17 37 PM](https://user-images.githubusercontent.com/33336127/168912047-db1faa9b-b782-430c-8a43-e4ce4463f984.png)
 In their figure legend, it describes "Proportional expression of the top 45 AD GWAS genes across all major brain cell types. Expression values for a given gene sums to 1 across cell types using the EWCE method. Genes ordered in approximate risk strength39–41,51. Asterisks denote the strongest expressing cell types."
 I am thinking about doing similar things, if you have this feature implemented.

Thanks!

**Comment by Al-Murphy** [comment]
Hey!

To go from GWAS SNPs to instigated cell types have a look at [MAGMA celltyping](https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/neurogenomics/MAGMA_Celltyping&ved=2ahUKEwjM1bfEvuj3AhXlgnIEHbZLBKcQFnoECAcQAQ&sqi=2&usg=AOvVaw0q0zXFNGNizopvQeHBGWVt) which was also developed in our lab. This package uses EWCE once it relates SNPs to genes. Have a look at the documentation and vignettes there and you will find what you're looking for. Unfortunately you will need to plot the heatplot yourself as it isn't a standard output but the data is all there.

Cheers,
Alan.
