### ISSUE TITLE
generate.celltype.data（）

### ISSUE THREAD

**Issue by yipingLin** [NathanSkene/EWCE#7]
I got an error when running function generate.celltype.data(),
`Error in mclapply(ctd, calculate.meanexp.for.level, exp, mc.cores = no_cores) : 
  'mc.cores' > 1 is not supported on Windows`
Does it only run on Linux systems?

**Comment by NathanSkene** [comment]
Hi, unfortunately the parallel package only really works on linux systems. No biggie though, just pass no_cores=1 to the generate.celltype.data function.

**Comment by yipingLin** [comment]
Thank you for your reply! @NathanSkene
