### ISSUE TITLE
Extracting genes driving the enrichment and their mean bootstrap expression

### ISSUE THREAD

**Issue by iscastanho** [NathanSkene/EWCE#76]
I am not sure if these are already features of EWCE (although I could not find in manuals/tutorials), so I am posting them as questions.

**1. Is there a way of extracting which genes are driving the enrichment for each cell type tested?**
At the moment I am using the “marker” genes for each population/subpopulation I have (which I identified with Seurat) but I was wondering if there was a way of extracting this directly from EWCE as I can see that it performs differential expression as part of the pipeline (using LIMMA if I noticed it correctly).

**2. Can I get the mean bootstrap expression for each gene from EWCE? If so, how?**
In Skene and Grant, 2016 (https://doi.org/10.3389/fnins.2016.00016), in Figure 2 C and D, genes from one of the cell types (microglia) are shown, highlighting their expression against the mean bootstrap expression. I would like to have access to this type of information from my data too. How could I extract this?

Thank you.

**Comment by NathanSkene** [comment]
EWCE can generate bootstrap plots that show the bootstrap probabilities of each gene. I thibk the function is something like generate bootstrap plots. I don't really find them that useful but regularly get asked which genes are driving the enrichments, and this is the clearest way of getting at it... but the enrichment is driven by the set of genes, not any particular gene

________________________________

**Comment by bschilder** [comment]
Here's the function @iscastanho 
https://nathanskene.github.io/EWCE/reference/generate_bootstrap_plots.html

See here for some upgrades I'm making to it soon.
#77
