### ISSUE TITLE
Error using DESeq2 Wald test for `drop_uninformative_genes()`

### ISSUE THREAD

**Issue by cyouh95** [NathanSkene/EWCE#81]
## 1. Bug description

Getting below error when specifying `dge_method = 'deseq2'` and `dge_test = 'Wald'` for `drop_uninformative_genes()`.

### Console output 

```
Error in DESeq2::DESeq(dds, test = test, reduced = ~1, parallel = no_cores >  : 
  'reduced' ignored when test='Wald'
```

### Expected behaviour   

It seems the `reduced` argument mentioned in the error message is only applicable to the default `dge_test = 'LRT'`.

**Comment by bschilder** [comment]
Hi @cyouh95 , 

It seems this argument was exposed to users in error. This feature has not yet been fully tested and thus shouldn't be used (EWCE only supports "limma" currently).

Second, in the future could you please fill out the rest of the bug report template? seems you're missing most of it, which makes it hard for us to address any bugs.
