### ISSUE TITLE
How do I analyze a Seurat object?

### ISSUE THREAD

**Issue by jmzhang1911** [NathanSkene/EWCE#94]
Thank you for developing such an excellent tool! I'm curious about how to directly analyze a Seurat object. Looking forward to your reply!

**Comment by NathanSkene** [comment]
You just need to find the matrix within the Seurat object that represents gene expression, and follow the tutorial for creating a CTD

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: jmzhang1911 ***@***.***>
Sent: Friday, April 19, 2024 7:31:18 AM
To: NathanSkene/EWCE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NathanSkene/EWCE] How do I analyze a Seurat object? (Issue #94)


This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Thank you for developing such an excellent tool! I'm curious about how to directly analyze a Seurat object. Looking forward to your reply!

**Comment by bschilder** [comment]
@jmzhang1911 `Seurat` has a function to convert Seurat objects to SingleCellExperiment format: 
`Seurat::as.SingleCellExperiment` 

`SingleCellExperiment` objects can then be used as input to `EWCE::generate_celltype_data` to generate your CTD reference for `EWCE` analyses.
